format_version: 10
pipelines:
  pipeline_code:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-e9d8817:
        git: https://github.com/wfejj/sample-web-application
        username: wfejj
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:akK2ut9gKoHXrzRF6nlfrg==:ChxS7KTM25wF7ojHmzkV9g==
    stages:
    - test_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test_job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                command: mvn
                run_if: passed
